### ISSUE TITLE
Migration is renaming ethernet connectors

### ISSUE THREAD

**Issue by matheusafernandes** [plesk/centos2alma#230]
The migration failed but when we tried to connect again through SSH we saw that the IPv4 was not attached to the eth0. In the "IP a" we see that the eth0 doesn't exist, the ethernet adapter was renamed to ens4. And we have to rebuild the network to get the files.

![Screenshot from 2024-04-04 09-35-51](https://github.com/plesk/centos2alma/assets/63871232/f34bb124-1b63-4067-b831-f6187abebafb)
[centos2alma_feedback.zip](https://github.com/plesk/centos2alma/files/14876311/centos2alma_feedback.zip)
[centos2alma.log](https://github.com/plesk/centos2alma/files/14876312/centos2alma.log)

**Comment by SandakovMM** [comment]
Based on centos2alma logs I could see dnf has been failed on update:
`
2024-03-27 16:42:46,901 - INFO - Running: ['/usr/bin/dnf', '-y', 'update']. Output:
2024-03-27 16:42:47,142 - INFO - Traceback (most recent call last):
2024-03-27 16:42:47,143 - INFO - File "/usr/bin/dnf", line 57, in <module>
2024-03-27 16:42:47,145 - INFO - from dnf.cli import main
2024-03-27 16:42:47,145 - INFO - File "/usr/lib/python2.7/site-packages/dnf/__init__.py", line 30, in <module>
2024-03-27 16:42:47,146 - INFO - import dnf.base
2024-03-27 16:42:47,146 - INFO - File "/usr/lib/python2.7/site-packages/dnf/base.py", line 29, in <module>
2024-03-27 16:42:47,147 - INFO - import libdnf.transaction
2024-03-27 16:42:47,147 - INFO - File "/usr/lib64/python2.7/site-packages/libdnf/__init__.py", line 3, in <module>
2024-03-27 16:42:47,148 - INFO - from . import conf
2024-03-27 16:42:47,148 - INFO - File "/usr/lib64/python2.7/site-packages/libdnf/conf.py", line 17, in <module>
2024-03-27 16:42:47,149 - INFO - _conf = swig_import_helper()
2024-03-27 16:42:47,149 - INFO - File "/usr/lib64/python2.7/site-packages/libdnf/conf.py", line 16, in swig_import_helper
2024-03-27 16:42:47,149 - INFO - return importlib.import_module('_conf')
2024-03-27 16:42:47,149 - INFO - File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
2024-03-27 16:42:47,150 - INFO - __import__(name)
2024-03-27 16:42:47,150 - INFO - ImportError: No module named _conf
2024-03-27 16:42:47,168 - ERROR - Command '['/usr/bin/dnf', '-y', 'update']' failed with return code 1
`
Don't you have any customization in yum configuration?

**Comment by SandakovMM** [comment]
As far as I understand, leapp does not ensure the stability of NIC interface names. Details could be found on the [red hat customer portal](https://access.redhat.com/solutions/4067471).
However leapp allows to perform the conversion if there is only one NIC interface. So I expect them to prevent problems in this case.
