### ISSUE TITLE
Upgrade doesn't start.  Error message in

### ISSUE THREAD

**Issue by tadosborn** [plesk/centos2alma#241]
2024-04-19 16:27:07,387 - ERROR - list index out of range
2024-04-19 16:27:07,388 - ERROR - Please fix noted problems before proceed the conversion
[centos2alma_feedback.zip](https://github.com/plesk/centos2alma/files/15046041/centos2alma_feedback.zip)

I'd greatly appreciate any assistance.

**Comment by tadosborn** [comment]
I ran the precheck with the upgrade process for Almalinux and it puked on the /etc/sshd/sshd_config file as there were some errors.  Fixed errors and will try again!

**Comment by tadosborn** [comment]
Issue with /etc/named.conf file:

====> * check_bind
        Actor parsing BIND configuration and checking for known issues in it.
Process Process-488:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/checkbind/actor.py", line 32, in process
    facts = iscmodel.get_facts('/etc/named.conf')
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/checkbind/libraries/iscmodel.py", line 81, in get_facts
    parser.walk(cfg.root_section(), find_calls, state)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 879, in walk
    for statement in it:
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 223, in __next__
    statement = next(self.iter)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 181, in __next__
    val = self.parser.find_next_key(cfg, index, self.section.end)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 689, in find_next_key
    while istr[index] in self.CHAR_KEYWORD and index < end_index:
IndexError: string index out of range

**Comment by SandakovMM** [comment]
> I ran the precheck with the upgrade process for Almalinux and it puked on the /etc/sshd/sshd_config file as there were some errors. Fixed errors and will try again!

Could you please tell what exactly was changed to fix the problem?

> Issue with /etc/named.conf file:

Could you please provide the file

**Comment by SandakovMM** [comment]
Hello Tad,

>  Ultimately, I’ll need PHP 5.3 for one website functional (possibly a Docker) in order to get the upgrade done.  I think I will build a brand new server and do a migration so that I can have a clean start on a new system

You right, if you want to use PHP 5.3, it might be better to migrate rather than convert in order to keep your website on the old server and only migrate other websites.
The support for older versions of PHP is a known issue for modern distros, we are researching solutions. However, at the moment, Plesk on AlmaLinux 8 does not support PHP versions older than 7.1, so we can't keep it on conversion. And prevent conversion if any website on your server use it.

> Do you have any suggestions on how to accomplish?

As far as I remember, you can install PHP 5.3 on AlmaLinux and then add it to the Plesk panel on a separate server, and migrate all websites to the server. But the installation process might be a bit difficult. You can find the guide on adding custom handlers in Plesk here: https://docs.plesk.com/en-US/obsidian/administrator-guide/web-hosting/php-management/adding-custom-php-versions-linux. You can also seek assistance from the Plesk support team.

Best regards

**Comment by SandakovMM** [comment]
I have provided several fixes for the missing includes in the named.conf in #361 and #362, so the problem with named.conf should now be resolved
