### ISSUE TITLE
Resume Upgrade

### ISSUE THREAD

**Issue by lecneri** [plesk/centos2alma#278]
As you told me in #267 I`ve executed the following command
`centos2alma --finish --state-dir /usr/local/psa/var/centos2alma --resume --verbose --log-file /var/log/plesk/centos2alma.log`
but it wasn't able to resume upgrade because it didn't find resume.json. What can I do to check and finish upgrade?
I tried search the resume.json but didn't find any
`[root@cadillac upgrade]# ./centos2alma --finish --state-dir /usr/local/psa/var/centos2alma --resume --verbose --log-file /var/log/plesk/centos2alma.log
Couldn't resume from '/usr/local/psa/var/centos2alma/resume.json': [Errno 2] No such file or directory: '/usr/local/psa/var/centos2alma/resume.json'
Traceback (most recent call last):
  File "/root/upgrade/centos2alma/pleskdistup/main.py", line 424, in main
    resume_data = read_resume_data(options.resume_path)
  File "/root/upgrade/centos2alma/pleskdistup/main.py", line 285, in read_resume_data
    with open(resume_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/psa/var/centos2alma/resume.json'`

**Comment by lecneri** [comment]
Thank you so much, I resumed the installation, and it didn't do much. But now I know it's done.
I couldn't finish it without your help. Thanks again
