### ISSUE TITLE
Centos2alma unable to parce mariadb version string in verbose mode

### ISSUE THREAD

**Issue by SandakovMM** [plesk/centos2alma#397]
The issue occurs when the MariaDB version output lacks the "Distrib" substring, and we activate centos2alma in verbose mode (-v). 
This is due to our [expectation to find the substring](https://github.com/plesk/dist-upgrader/blob/508dbf9ae8a1d4855b1cdfa1bc9ee89db4d73ef7/pleskdistup/common/src/mariadb.py#L91) whenever parsing the MariaDB version output. Instead, the process should transition to using the MaridbVersion class.

**Comment by nicholsjl** [comment]
Hi @SandakovMM, I'm encountering this error with or without the --verbose option after I manually upgraded MariaDB to 11.4. Is it related to this ticket? Is there a fix or workaround?

```
Doing preparation checks...
Preparation checks failed: Exception during checking of required pre-conversion condition 'check mariadb repo available'
Traceback (most recent call last):
  File "/home/jodi/centos2alma/pleskdistup/common/src/action.py", line 473, in make_checks
    if not check.do_check():
  File "/home/jodi/centos2alma/pleskdistup/common/src/action.py", line 445, in do_check
    return self._do_check()
  File "centos2almaconverter/actions/mariadb.py", line 26, in _do_check
    if not mariadb.is_mariadb_installed() or not mariadb.get_installed_mariadb_version() > MARIADB_VERSION_ON_ALMA:
  File "/home/jodi/centos2alma/pleskdistup/common/src/mariadb.py", line 91, in get_installed_mariadb_version
    log.debug("Detected mariadb version is: {version}".format(version=out.split("Distrib ")[1].split(",")[0].split("-")[0]))
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pleskdistup/main.py", line 128, in required_conditions_satisfied
    failed_checks = check_flow.make_checks()
  File "/home/jodi/centos2alma/pleskdistup/common/src/action.py", line 476, in make_checks
    raise RuntimeError(f"Exception during checking of required pre-conversion condition {check.name!r}") from e
RuntimeError: Exception during checking of required pre-conversion condition 'check mariadb repo available'

Conversion can't be performed due to the problems noted above
```

The output of `mariadb --version` is as follows:
`mariadb from 11.4.3-MariaDB, client 15.2 for Linux (x86_64) using readline 5.1`

Prior to upgrading to 11.4 the output was:
`mariadb  Ver 15.1 Distrib 10.11.9-MariaDB, for Linux (x86_64) using readline 5.1`

**Comment by SandakovMM** [comment]
> Is it related to this ticket?

Yes, it is likely related

> Is there a fix or workaround?

The issue should be fixed in [v1.4.5](https://github.com/plesk/centos2alma/releases/tag/v1.4.5)

**Comment by SandakovMM** [comment]
The problem should be fixed in scope of #409
